# NUMPY Project Exercise

By- A.Yash Kumar Rao

# Guidelines:

1. This Assignment is mandatory for everyone.

2. Use the below sample table to solve the below queries.

3. It is mandatory to submit the answer with the screen shot of the output you have received. Otherwise, no marks will be given.

4. If anyone fails to submit the assignment within the last date. His/her assignment submission will not be evaluated and will be allotted minus marks also.

# Questions:

In [1]:
import numpy as np

In [2]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/installation file\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/installation file\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/installation file\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/i

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


In [5]:
numpy.info(numpy.add)

NameError: name 'numpy' is not defined

In [61]:
a= np.zeros(10)
a[4]= 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [60]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [59]:
a = np.arange(10,50)
a= a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [58]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
a = np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int64),)

In [56]:
a= np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
a = np.random.uniform((3,3,3))
a

array([2.76851232, 2.66743721, 2.8376697 ])

In [54]:
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.01679823823020965 0.9955488899075445


In [53]:
a = np.random.random(10)
m = a.mean()
print (m)

0.5288069896453468


In [52]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
a = np.ones((5,5))
a = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
print(0 * np.nan) 
print(np.nan == np.nan) 
print(np.inf > np.nan) 
print(np.nan - np.nan) 
print(np.nan in set([np.nan])) 
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [49]:
a = np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [48]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [6]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [7]:
a = np.tile( np.array([[0,1],[1,0]]), (4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [47]:
a = np.random.random((5,5))
a = (Z - np.mean (Z)) / (np.std (Z))
a

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [46]:
a = np.random.randint(0,10,50)
print(np.bincount(a).argmax())

1


In [45]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [43]:
a = np.arange(11)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [42]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [41]:
Z <- Z
1j*Z
Z/1/1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
import warnings
warnings.simplefilter('ignore')


print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


# <ipython-input-20-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
#   print(np.array(0) / np.array(0))
# <ipython-input-20-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
#   print(np.array(0) // np.array(0))

nan
0
[-2.14748365e+09]


In [ ]:
a = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

30. How to find common values between two arrays?

In [65]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[3 7]


In [64]:
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
mat_sort = mat[mat[:,2].argsort()]
print(mat_sort)

[[ 5  4  2]
 [ 1 21  3]
 [56 12  4]]


In [63]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [62]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday =", yesterday,"\n",
      "today =", today,"\n",
      "tomorrow =", tomorrow)

yesterday = 2020-09-03 
 today = 2020-09-04 
 tomorrow = 2020-09-05


In [9]:
a = np.arange('2020-07', '2020-08', dtype='datetime64[D]')
a

array(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
       '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
       '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
       '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
       '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
       '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
       '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
       '2020-07-29', '2020-07-30', '2020-07-31'], dtype='datetime64[D]')

In [10]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [11]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[8. 7. 3. 6. 7. 2. 9. 0. 3. 7.]
[8. 7. 3. 6. 7. 2. 9. 0. 3. 7.]
[8. 7. 3. 6. 7. 2. 9. 0. 3. 7.]
[8 7 3 6 7 2 9 0 3 7]
[8. 7. 3. 6. 7. 2. 9. 0. 3. 7.]


In [12]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [13]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [14]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [15]:
a = np.random.random(10)
a.sort()
print(a)

[0.02086308 0.17924879 0.18990033 0.23466803 0.28395784 0.36243361
 0.57800312 0.70302301 0.74105982 0.94385777]


In [16]:
a = np.arange(10)
np.add.reduce(a)

45

In [17]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [34]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

In [31]:
a = np.random.random((10,2))
X,Y = a[:,0], a[:,1]
b = np.sqrt(X**2+Y**2)
c = np.arctan2(Y,X)
print(b)
print(c)

[0.75558258 0.76098238 0.51618282 0.66899815 0.19264364 0.31730324
 0.18598813 0.98376932 0.46046425 0.08831271]
[0.10658305 0.37150715 1.56221203 0.69521308 1.4302822  0.04076642
 1.30600049 0.18169978 1.11635795 0.8660336 ]


In [30]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.34293023 0.88917765 0.37828478 0.58837493 0.09675722 0.5714703
 0.35605196 0.8317772  0.07474442 0.        ]


In [29]:
a = np.arange(8)
b = a + 0.5
c = 1.0 / np.subtract.outer(a, b)
print(np.linalg.det(c))

3638.1636371179666


In [23]:
pd.read()

SyntaxError: invalid syntax (<ipython-input-23-d2264bdcc637>, line 2)

In [27]:
a = np.random.rand(5, 10)
b = a - a.mean(axis=1, keepdims=True)
b = a - a.mean(axis=1).reshape(-1, 1)
print(b)

[[-0.27750052  0.43070603 -0.01386178  0.10400049  0.3963023  -0.06550521
  -0.31152056 -0.33240023 -0.20858639  0.27836587]
 [-0.07401436 -0.13990231 -0.27540373  0.11939493  0.32389089  0.13750721
   0.43178482 -0.22529401  0.01525275 -0.31321621]
 [ 0.05586642  0.15109252  0.05396199 -0.32794126  0.29625643  0.34720582
  -0.26220495  0.11002152 -0.33587036 -0.08838813]
 [ 0.2576004  -0.37479499  0.13376124 -0.04613322  0.04391521 -0.33389131
   0.20598887 -0.02232411  0.00955939  0.1263185 ]
 [-0.25554628  0.3237941  -0.14077281  0.42172484  0.28593471 -0.56456696
   0.14584381 -0.20401682 -0.03604059  0.02364599]]


In [25]:
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

False


In [26]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
